export type RoleType = 'ai' | 'fullstack' | 'other';

export type Site = {
  /** slug = sibling repo suffix, drives /logos/<id>.png and /shots/<id>.webp */
  id: string;
  company: string;
  role: string;
  roleType: RoleType;
  /** live application site; qbiq's typo'd URL is canonical */
  url: string;
  /** the company's real domain; feeds the logo fetch script only */
  domain: string;
  /** brand accent, tints the logo tile */
  accent: string;
  /** optional solid tile background, for logos designed for dark surfaces */
  tile?: string;
  tagline: string;
  /** ISO date, newest first in the grid */
  appliedOn: string;
};

export const SITES: Site[] = [
  {
    id: 'netflix',
    company: 'Netflix',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-netflix.vercel.app',
    domain: 'netflix.com',
    accent: '#E50914',
    tile: '#141414',
    tagline: 'The browse UI: a billboard hero and a Top 10 row of builds.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'amazon',
    company: 'Amazon',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-amazon.vercel.app',
    domain: 'amazon.com',
    accent: '#FF9900',
    tile: '#131921',
    tagline: 'The retail homepage, with a search bar that really filters the work.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'airbnb',
    company: 'Airbnb',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-airbnb.vercel.app',
    domain: 'airbnb.com',
    accent: '#FF385C',
    tagline: 'Listing carousels with hearts, ratings, and a working pill search.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'waze',
    company: 'Waze',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-waze.vercel.app',
    domain: 'waze.com',
    accent: '#33CCFF',
    tagline: 'Their bento color cards, with original Wazer characters bobbing.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'wix',
    company: 'Wix',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-wix.vercel.app',
    domain: 'wix.com',
    accent: '#166AEA',
    tagline: 'Giant Madefor type and a live editor building the application.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'microsoft',
    company: 'Microsoft',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-microsoft.vercel.app',
    domain: 'microsoft.com',
    accent: '#0067B8',
    tile: '#ffffff',
    tagline: 'Fluent product cards and a working hero carousel.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'google',
    company: 'Google',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-google.vercel.app',
    domain: 'google.com',
    accent: '#4285F4',
    tagline: 'Their search page, replicated: my work as the results.',
    appliedOn: '2026-07-05',
  },
  {
    id: 'facebook',
    company: 'Facebook',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-facebook.vercel.app',
    domain: 'facebook.com',
    accent: '#0866FF',
    tagline: 'The logged-in feed, replicated: every post a shipped project.',
    appliedOn: '2026-07-05',
  },
  {
    id: 'apple',
    company: 'Apple',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-apple.vercel.app',
    domain: 'apple.com',
    accent: '#1d1d1f',
    tagline: 'Their product-tile wall, with my work as the lineup.',
    appliedOn: '2026-07-05',
  },
  {
    id: 'nym',
    company: 'Nym',
    role: 'Software Engineer (Engine)',
    roleType: 'fullstack',
    url: 'https://bar-for-nym.vercel.app',
    domain: 'nym.health',
    accent: '#03B5E1',
    tagline: 'Their navy engine room, redrawn dash streams and all.',
    appliedOn: '2026-07-05',
  },
  {
    id: 'joomsy',
    company: 'Joomsy',
    role: 'Application site',
    roleType: 'other',
    url: 'https://bar-for-joomsy.vercel.app',
    domain: 'joomsy.com',
    accent: '#FFCC00',
    tagline: 'Their googly-eyed yellow world, every graphic hand-drawn.',
    appliedOn: '2026-07-05',
  },
  {
    id: 'guardio',
    company: 'Guardio',
    role: 'Fullstack Growth Engineer',
    roleType: 'fullstack',
    url: 'https://bar-for-guardio.vercel.app',
    domain: 'guard.io',
    accent: '#2E69FF',
    tagline: 'Floating proof cards in their pill-and-navy language.',
    appliedOn: '2026-07-05',
  },
  {
    id: 'alice',
    company: 'Alice',
    role: 'AI Software Engineer',
    roleType: 'ai',
    url: 'https://bar-for-alice.vercel.app',
    domain: 'alice.io',
    accent: '#108496',
    tagline: 'Wonderland brand with hand-coded SVG illustrations.',
    appliedOn: '2026-07-05',
  },
  {
    id: 'autofleet',
    company: 'Autofleet',
    role: 'Full Stack Developer',
    roleType: 'fullstack',
    url: 'https://bar-for-autofleet.vercel.app',
    domain: 'autofleet.io',
    accent: '#11A4FF',
    tagline: 'Their isometric city, redrawn as original SVG.',
    appliedOn: '2026-07-05',
  },
  {
    id: 'unframe',
    company: 'Unframe',
    role: 'Full Stack Software Engineer',
    roleType: 'fullstack',
    url: 'https://bar-for-unframe.vercel.app',
    domain: 'unframe.ai',
    accent: '#191919',
    tagline: 'Black and white bands with their signature gradient.',
    appliedOn: '2026-07-05',
  },
  {
    id: 'honeybook',
    company: 'HoneyBook',
    role: 'AI-native Builder',
    roleType: 'ai',
    url: 'https://bar-for-honeybook.vercel.app',
    domain: 'honeybook.com',
    accent: '#FFFA56',
    tagline: 'The pattern-setter: their clientflow look, my work grid.',
    appliedOn: '2026-07-04',
  },
  {
    id: 'aidome',
    company: 'Aidome',
    role: 'Full Stack Engineer, AI',
    roleType: 'fullstack',
    url: 'https://bar-for-aidome.vercel.app',
    domain: 'aidome.co',
    accent: '#ff003c',
    tagline: 'Their crimson control-plane language, my full stack proof.',
    appliedOn: '2026-07-03',
  },
  {
    id: 'classiq',
    company: 'Classiq',
    role: 'Software Engineer',
    roleType: 'other',
    url: 'https://bar-for-classiq.vercel.app',
    domain: 'classiq.io',
    accent: '#d7f75b',
    tagline: 'Quantum brand with their lime pills and circuit motif.',
    appliedOn: '2026-07-03',
  },
  {
    id: 'flare',
    company: 'Flare',
    role: 'AI Engineer',
    roleType: 'ai',
    url: 'https://bar-for-flare.vercel.app',
    domain: 'helloflare.com',
    accent: '#5b8a68',
    tagline: 'Their editorial serif calm with an agent-flow demo.',
    appliedOn: '2026-07-03',
  },
  {
    id: 'genielabs',
    company: 'GenieLabs',
    role: 'Full Stack Engineer',
    roleType: 'fullstack',
    url: 'https://bar-for-genielabs.vercel.app',
    domain: 'genielabs.tech',
    accent: '#FF1C74',
    tagline: 'Hot-pink LiveOps energy for game-studio content.',
    appliedOn: '2026-07-03',
  },
  {
    id: 'guidde',
    company: 'Guidde',
    role: 'Full Stack Engineer',
    roleType: 'fullstack',
    url: 'https://bar-for-guidde.vercel.app',
    domain: 'guidde.com',
    accent: '#0062FF',
    tagline: 'Their blue video-doc brand with a walkthrough player.',
    appliedOn: '2026-07-03',
  },
  {
    id: 'monday',
    company: 'monday.com',
    role: 'AI Software Engineer, RevAI',
    roleType: 'ai',
    url: 'https://bar-for-monday.vercel.app',
    domain: 'monday.com',
    accent: '#6161FF',
    tagline: 'Their live brand and a RevAI lead-qualification canvas.',
    appliedOn: '2026-07-03',
  },
  {
    id: 'qbiq',
    company: 'qbiq',
    role: 'Full Stack Developer',
    roleType: 'fullstack',
    url: 'https://bar-for-qbit.vercel.app',
    domain: 'qbiq.ai',
    accent: '#0040ff',
    tagline: 'Their perspective rays over a real-estate AI story.',
    appliedOn: '2026-07-03',
  },
  {
    id: 'descope',
    company: 'Descope',
    role: 'Full Stack Software Engineer',
    roleType: 'fullstack',
    url: 'https://bar-for-descope.vercel.app',
    domain: 'descope.com',
    accent: '#7DEDED',
    tagline: 'Their mint identity language, hexagon keys and all.',
    appliedOn: '2026-07-02',
  },
  {
    id: 'jeen-ai',
    company: 'Jeen.AI',
    role: 'Full Stack Engineer',
    roleType: 'fullstack',
    url: 'https://bar-for-jeen-ai.vercel.app',
    domain: 'jeen.ai',
    accent: '#dd9fe2',
    tagline: 'Cream and lilac enterprise AI with a governed-answer console.',
    appliedOn: '2026-07-02',
  },
  {
    id: 'esquare',
    company: 'e-square',
    role: 'Full Stack Developer',
    roleType: 'fullstack',
    url: 'https://bar-for-esquare.vercel.app',
    domain: 'e-square.io',
    accent: '#22d3ee',
    tagline: 'Glassmorphism and gradients in their Angular world.',
    appliedOn: '2026-07-01',
  },
  {
    id: 'jfrog',
    company: 'JFrog',
    role: 'GenAI and Competitive Intelligence Engineer',
    roleType: 'ai',
    url: 'https://bar-for-jfrog.vercel.app',
    domain: 'jfrog.com',
    accent: '#40BE46',
    tagline: 'Pipeline-flow graphics in JFrog green.',
    appliedOn: '2026-07-01',
  },
  {
    id: 'play48',
    company: 'Play48',
    role: 'Full Stack Game Engineer',
    roleType: 'fullstack',
    url: 'https://bar-for-play48.vercel.app',
    domain: 'play48.ai',
    accent: '#ee6a2c',
    tile: '#221610',
    tagline: 'Playable 2048 as the centerpiece.',
    appliedOn: '2026-06-30',
  },
  {
    id: 'prologic',
    company: 'Prologic',
    role: 'Full Stack Developer',
    roleType: 'fullstack',
    url: 'https://bar-for-prologic.vercel.app',
    domain: 'prologic.co.il',
    accent: '#f36f22',
    tagline: 'Their gear brand as a GenAI pipeline, right to left.',
    appliedOn: '2026-06-30',
  },
  {
    id: 'echo',
    company: 'Echo',
    role: 'Full Stack GenAI Engineer',
    roleType: 'ai',
    url: 'https://bar-for-echo.vercel.app',
    domain: 'echo.ai',
    accent: '#6aa7ff',
    tagline: 'Their iridescent palette over a full stack GenAI story.',
    appliedOn: '2026-06-30',
  },
  {
    id: 'orca',
    company: 'Orca AI',
    role: 'AI Systems Engineer',
    roleType: 'ai',
    url: 'https://bar-for-orca.vercel.app',
    domain: 'orca-ai.io',
    accent: '#5fe3d5',
    tagline: 'Navy ocean with a WebGL whale-tail shader.',
    appliedOn: '2026-06-30',
  },
  {
    id: 'ourritual',
    company: 'OurRitual',
    role: 'Generative AI Engineer',
    roleType: 'ai',
    url: 'https://bar-for-ourritual.vercel.app',
    domain: 'ourritual.com',
    accent: '#e5654b',
    tagline: 'Their warm palette around generative AI work.',
    appliedOn: '2026-06-30',
  },
  {
    id: 'psistar',
    company: 'Psistar',
    role: 'Software Engineer',
    roleType: 'other',
    url: 'https://bar-for-psistar.vercel.app',
    domain: 'psistar.ai',
    accent: '#7886e8',
    tagline: 'Psi-field motif in their periwinkle.',
    appliedOn: '2026-06-30',
  },
  {
    id: 'datadog',
    company: 'Datadog',
    role: 'Software Engineer, AI Developer Workflows',
    roleType: 'ai',
    url: 'https://bar-for-datadog.vercel.app',
    domain: 'datadoghq.com',
    accent: '#632ca6',
    tagline: 'Their purple observability style as a light dashboard.',
    appliedOn: '2026-06-29',
  },
  {
    id: 'tenable',
    company: 'Tenable',
    role: 'Full Stack Engineer, Integrations Frameworks',
    roleType: 'fullstack',
    url: 'https://bar-for-tenable.vercel.app',
    domain: 'tenable.com',
    accent: '#d6f84c',
    tagline: 'Lime on charcoal with a rotating heptagon mark.',
    appliedOn: '2026-06-29',
  },
  {
    id: 'aidoc',
    company: 'Aidoc',
    role: 'Generative AI Engineer',
    roleType: 'ai',
    url: 'https://bar-for-aidoc.vercel.app',
    domain: 'aidoc.com',
    accent: '#060C40',
    tagline: 'Clinical-AI brand with my AI pipeline work up front.',
    appliedOn: '2026-06-28',
  },
  {
    id: 'cheq',
    company: 'CHEQ',
    role: 'AI Engineer',
    roleType: 'ai',
    url: 'https://bar-for-cheq.vercel.app',
    domain: 'cheq.ai',
    accent: '#fd0173',
    tagline: 'Their dark intelligence brand, hot-pink gradients included.',
    appliedOn: '2026-06-28',
  },
  {
    id: 'cover',
    company: 'Cover',
    role: 'AI Full Stack Developer',
    roleType: 'ai',
    url: 'https://bar-for-cover.vercel.app',
    domain: 'cover.co.il',
    accent: '#0153f4',
    tagline: 'Their navy insurtech look with a periwinkle glow.',
    appliedOn: '2026-06-28',
  },
  {
    id: 'cytactic',
    company: 'Cytactic',
    role: 'AI Engineer',
    roleType: 'ai',
    url: 'https://bar-for-cytactic.vercel.app',
    domain: 'cytactic.com',
    accent: 'oklch(0.56 0.235 289)',
    tagline: 'Threat-response violet with a live incident feel.',
    appliedOn: '2026-06-28',
  },
  {
    id: 'deloitte',
    company: 'Deloitte',
    role: 'Full Stack Engineer, R&D and Innovation Center',
    roleType: 'fullstack',
    url: 'https://bar-for-deloitte.vercel.app',
    domain: 'deloitte.com',
    accent: '#86BC25',
    tagline: 'The green Big Four brand around GenAI and RAG work.',
    appliedOn: '2026-06-28',
  },
  {
    id: 'hio',
    company: 'HiO',
    role: 'Full Stack Engineer',
    roleType: 'fullstack',
    url: 'https://bar-for-hio.vercel.app',
    domain: 'hio.ai',
    accent: '#0040ff',
    tagline: 'A working mini HiO inbox in their own brand.',
    appliedOn: '2026-06-28',
  },
  {
    id: 'novella',
    company: 'Novella',
    role: 'AI Engineer',
    roleType: 'ai',
    url: 'https://bar-for-novella.vercel.app',
    domain: 'bynovella.com',
    accent: '#371D41',
    tagline: 'Plum and gold for an AI-native brokerage.',
    appliedOn: '2026-06-28',
  },
  {
    id: 'playojo',
    company: 'PlayOJO',
    role: 'Frontend / Game Developer',
    roleType: 'other',
    url: 'https://bar-for-playojo.vercel.app',
    domain: 'playojo.com',
    accent: '#4921c5',
    tagline: 'A fully playable Phaser slot game.',
    appliedOn: '2026-06-28',
  },
  {
    id: 'questar',
    company: 'Questar',
    role: 'Full Stack Developer',
    roleType: 'fullstack',
    url: 'https://bar-for-questar.vercel.app',
    domain: 'questarauto.com',
    accent: '#240046',
    tagline: 'Indigo fleet-health brand with gradient accents.',
    appliedOn: '2026-06-28',
  },
  {
    id: 'willow',
    company: 'Willow',
    role: 'Forward Deployed Engineer',
    roleType: 'other',
    url: 'https://bar-for-willow.vercel.app',
    domain: 'withwillow.ai',
    accent: 'oklch(0.68 0.15 145)',
    tagline: 'An animated isometric forest world.',
    appliedOn: '2026-06-28',
  },
  {
    id: 'openai',
    company: 'OpenAI',
    role: 'Generic application',
    roleType: 'ai',
    url: 'https://bar-for-openai.vercel.app',
    domain: 'openai.com',
    accent: '#000000',
    tile: '#ffffff',
    tagline: 'Their chat-input hero and story-card grid, reframed as my build pipeline.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'anthropic',
    company: 'Anthropic',
    role: 'Generic application',
    roleType: 'ai',
    url: 'https://bar-for-anthropic.vercel.app',
    domain: 'anthropic.com',
    accent: '#141413',
    tile: '#FAF9F5',
    tagline: 'Their warm editorial serif and a hand-drawn manuscript centerpiece.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'lovable',
    company: 'Lovable',
    role: 'Generic application',
    roleType: 'fullstack',
    url: 'https://bar-for-lovable.vercel.app',
    domain: 'lovable.dev',
    accent: '#FF6154',
    tagline: 'Their gradient blur and floating chat card, built as my brief-to-ship loop.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'intel',
    company: 'Intel',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-intel.vercel.app',
    domain: 'intel.com',
    accent: '#0046C8',
    tile: '#ffffff',
    tagline: 'A pinned chip-card carousel and a dot-matrix silicon motif.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'keshet',
    company: 'Keshet',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-keshet.vercel.app',
    domain: 'keshetinternational.com',
    accent: '#252b3d',
    tile: '#ffffff',
    tagline: 'Rebuilt as mako, Keshet’s Hebrew news portal, right to left.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'base44',
    company: 'Base44',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-base44.vercel.app',
    domain: 'base44.com',
    accent: '#FF6A00',
    tagline: 'A vibe-coding prompt box that builds the case for hiring me.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'wiz',
    company: 'Wiz',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-wiz.vercel.app',
    domain: 'wiz.io',
    accent: '#0254EC',
    tagline: 'Their blueprint line-art, redrawn as a live security graph.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'payoneer',
    company: 'Payoneer',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-payoneer.vercel.app',
    domain: 'payoneer.com',
    accent: '#7B3FE4',
    tagline: 'Their rainbow ring sweeping a clean white hero.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'figma',
    company: 'Figma',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-figma.vercel.app',
    domain: 'figma.com',
    accent: '#A259FF',
    tagline: 'A design canvas with my work already shipped on it.',
    appliedOn: '2026-07-06',
  },
];

export const logoOf = (s: Site) => `/logos/${s.id}.png`;
export const shotOf = (s: Site) => `/shots/${s.id}.webp`;
