export type RoleType = 'ai' | 'fullstack' | 'other';

export type Site = {
  /** slug = sibling repo suffix, drives /logos/<id>.png and /shots/<id>.webp */
  id: string;
  company: string;
  role: string;
  roleType: RoleType;
  /** live application site; qbiq's typo'd URL is canonical */
  url: string;
  /** the company's real domain; feeds the logo fetch script only */
  domain: string;
  /** brand accent, tints the logo tile */
  accent: string;
  /** optional solid tile background, for logos designed for dark surfaces */
  tile?: string;
  tagline: string;
  /** ISO date, newest first in the grid */
  appliedOn: string;
};

export const SITES: Site[] = [
  {
    id: 'qodo',
    company: 'Qodo',
    role: 'Applied AI Engineer, Partnerships',
    roleType: 'ai',
    url: 'https://bar-for-qodo.vercel.app',
    domain: 'qodo.ai',
    accent: '#7968FA',
    tile: '#111013',
    tagline: 'Their near-black, purple-accented AI code-review brand, rebuilt around an honest Q&A that names the real gaps against the JD instead of papering over them.',
    appliedOn: '2026-07-12',
  },
  {
    id: 'temporal',
    company: 'Temporal',
    role: 'Generic application',
    roleType: 'ai',
    url: 'https://bar-for-temporal.vercel.app',
    domain: 'temporal.io',
    accent: '#8E5DFF',
    tile: '#141414',
    tagline: 'Their ultraviolet Durable Execution brand, rebuilt around the honest hook: three Temporal side projects, one featured on their own Code Exchange.',
    appliedOn: '2026-07-11',
  },
  {
    id: 'centrical',
    company: 'Centrical',
    role: 'AI Focused Full Stack Developer',
    roleType: 'ai',
    url: 'https://bar-for-centrical.vercel.app',
    domain: 'centrical.com',
    accent: '#E11C8E',
    tile: '#211551',
    tagline: 'Their indigo performance-OS brand, rebuilt around a five-step shipping accordion and the MCP hook: they just wired their platform into Claude, and MCP servers are the work on the page.',
    appliedOn: '2026-07-11',
  },
  {
    id: 'weunica',
    company: 'WeUnica',
    role: 'Junior Full-Stack Developer',
    roleType: 'fullstack',
    url: 'https://bar-for-weunica.vercel.app',
    domain: 'weunica.com',
    accent: '#55A4E4',
    tile: '#000000',
    tagline: 'Their strict black-and-white Montserrat brand, rebuilt around the rocket milestone trail: an e2e dev shop pitched by someone who ships e2e.',
    appliedOn: '2026-07-11',
  },
  {
    id: 'daisy',
    company: 'Daisy',
    role: 'Senior Developer, Agentic AI',
    roleType: 'ai',
    url: 'https://bar-for-daisy.vercel.app',
    domain: 'joindaisy.com',
    accent: '#006956',
    tagline: 'Their cream-and-green building OS brand, rebuilt around agent teammates with a human approval gate: the way they say they want to work is the way I already do.',
    appliedOn: '2026-07-11',
  },
  {
    id: 'novee-security',
    company: 'Novee',
    role: 'AI Engineer',
    roleType: 'ai',
    url: 'https://bar-for-novee-security.vercel.app',
    domain: 'novee.security',
    accent: '#8E55FD',
    tile: '#140945',
    tagline: 'Their dark neon-gym brand for offensive AI, rebuilt around an evaluation training loop and the eval harness the role is really about.',
    appliedOn: '2026-07-09',
  },
  {
    id: 'travelbooster',
    company: 'Travel Booster',
    role: 'AI Fullstack Developer',
    roleType: 'ai',
    url: 'https://bar-for-travelbooster.vercel.app',
    domain: 'travelbooster.com',
    accent: '#771FFF',
    tile: '#2A1052',
    tagline: 'Their deep-purple travel-ERP brand, rebuilt around their engine diagram and the LLM, MCP, and agent layer I ship.',
    appliedOn: '2026-07-09',
  },
  {
    id: 'walkme',
    company: 'WalkMe',
    role: 'Full Stack Engineer, AI Applications',
    roleType: 'fullstack',
    url: 'https://bar-for-walkme.vercel.app',
    domain: 'walkme.com',
    accent: '#FFFB4D',
    tile: '#0C0B40',
    tagline: 'Their navy-and-yellow DAP brand, rebuilt around their See/Unify/Execute verbs and the AI apps I ship.',
    appliedOn: '2026-07-09',
  },
  {
    id: 'anecdotes',
    company: 'anecdotes',
    role: 'Senior Backend Engineer, Data Platform',
    roleType: 'fullstack',
    url: 'https://bar-for-anecdotes.vercel.app',
    domain: 'anecdotes.ai',
    accent: '#00DCE8',
    tile: '#031926',
    tagline: 'Their AI-native GRC look, rebuilt as a CV around the Temporal orchestration and agents I ship.',
    appliedOn: '2026-07-09',
  },
  {
    id: 'varonis',
    company: 'Varonis',
    role: 'AI Platform & Adoption Specialist',
    roleType: 'ai',
    url: 'https://bar-for-varonis.vercel.app',
    domain: 'varonis.com',
    accent: '#0077FF',
    tile: '#010203',
    tagline: 'Their dark cosmic "Secure AI" brand, rebuilt around the AI-adoption hub and MCP tooling I ship.',
    appliedOn: '2026-07-07',
  },
  {
    id: 'moon-active',
    company: 'Moon Active',
    role: 'Full Stack Developer (R&D)',
    roleType: 'fullstack',
    url: 'https://bar-for-moon-active.vercel.app',
    domain: 'moonactive.com',
    accent: '#FFAD00',
    tile: '#000000',
    tagline: 'Their black-and-gold game brand, with a playable Coin Master-style mini-game I built to prove the role.',
    appliedOn: '2026-07-07',
  },
  {
    id: 'insait',
    company: 'Insait',
    role: 'LLM Solutions Engineer',
    roleType: 'ai',
    url: 'https://bar-for-insait.vercel.app',
    domain: 'insait.io',
    accent: '#3BC4B6',
    tile: '#F6F6F4',
    tagline: 'Their cream fintech console and channel-hub, rebuilt around my LLM workflow loop.',
    appliedOn: '2026-07-07',
  },
  {
    id: 'leo-ai',
    company: 'Leo AI',
    role: 'Full Stack Engineer',
    roleType: 'fullstack',
    url: 'https://bar-for-leo-ai.vercel.app',
    domain: 'getleo.ai',
    accent: '#3B60E2',
    tile: '#0E0B12',
    tagline: 'Their drafting-table serif dark, with my build loop drawn as fig. 1.',
    appliedOn: '2026-07-07',
  },
  {
    id: 'axia',
    company: 'Axia Security',
    role: 'Full Stack Engineer',
    roleType: 'fullstack',
    url: 'https://bar-for-axia.vercel.app',
    domain: 'axiasecurity.io',
    accent: '#14B8A6',
    tile: '#0D1117',
    tagline: 'Their radar-dark insider-risk manifesto, with my build loop on the scope.',
    appliedOn: '2026-07-07',
  },
  {
    id: 'torii',
    company: 'Torii',
    role: 'Junior Software Engineer',
    roleType: 'fullstack',
    url: 'https://bar-for-torii.vercel.app',
    domain: 'toriihq.com',
    accent: '#0054FF',
    tagline: 'Their SaaS/AI governance graph, rebuilt as my MCP integration flow.',
    appliedOn: '2026-07-07',
  },
  {
    id: 'primis',
    company: 'Primis',
    role: 'Full Stack / AI Engineer',
    roleType: 'fullstack',
    url: 'https://bar-for-mccann.vercel.app/primis',
    domain: 'primis.tech',
    accent: '#FF1455',
    tile: '#00152A',
    tagline: 'Their navy video-discovery world: a line-art lighthouse, an isometric player, me as the open position.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'mccann',
    company: 'McCann',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-mccann.vercel.app',
    domain: 'mccann.co.il',
    accent: '#3021F5',
    tile: '#141114',
    tagline: 'Their black-canvas agency site in Hebrew RTL, with me as job 05.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'tesla',
    company: 'Tesla',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-tesla.vercel.app',
    domain: 'tesla.com',
    accent: '#E82127',
    tile: '#171a20',
    tagline: 'Full-bleed cinematic slides, one per build, with their pill CTAs.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'fiverr',
    company: 'Fiverr',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-fiverr.vercel.app',
    domain: 'fiverr.com',
    accent: '#1DBF73',
    tagline: 'Their marketplace: a working search and my work as gig cards.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'lightricks',
    company: 'Lightricks',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-lightricks.vercel.app',
    domain: 'lightricks.com',
    accent: '#7C3AED',
    tile: '#0a0a0a',
    tagline: 'Grainy gradient-mesh cinematics with product-showcase cards.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'netflix',
    company: 'Netflix',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-netflix.vercel.app',
    domain: 'netflix.com',
    accent: '#E50914',
    tile: '#141414',
    tagline: 'The browse UI: a billboard hero and a Top 10 row of builds.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'amazon',
    company: 'Amazon',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-amazon.vercel.app',
    domain: 'amazon.com',
    accent: '#FF9900',
    tile: '#131921',
    tagline: 'The retail homepage, with a search bar that really filters the work.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'airbnb',
    company: 'Airbnb',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-airbnb.vercel.app',
    domain: 'airbnb.com',
    accent: '#FF385C',
    tagline: 'Listing carousels with hearts, ratings, and a working pill search.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'waze',
    company: 'Waze',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-waze.vercel.app',
    domain: 'waze.com',
    accent: '#33CCFF',
    tagline: 'Their bento color cards, with original Wazer characters bobbing.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'wix',
    company: 'Wix',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-wix.vercel.app',
    domain: 'wix.com',
    accent: '#166AEA',
    tagline: 'Giant Madefor type and a live editor building the application.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'microsoft',
    company: 'Microsoft',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-microsoft.vercel.app',
    domain: 'microsoft.com',
    accent: '#0067B8',
    tile: '#ffffff',
    tagline: 'Fluent product cards and a working hero carousel.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'google',
    company: 'Google',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-google.vercel.app',
    domain: 'google.com',
    accent: '#4285F4',
    tagline: 'Their search page, replicated: my work as the results.',
    appliedOn: '2026-07-05',
  },
  {
    id: 'facebook',
    company: 'Facebook',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-facebook.vercel.app',
    domain: 'facebook.com',
    accent: '#0866FF',
    tagline: 'The logged-in feed, replicated: every post a shipped project.',
    appliedOn: '2026-07-05',
  },
  {
    id: 'apple',
    company: 'Apple',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-apple.vercel.app',
    domain: 'apple.com',
    accent: '#1d1d1f',
    tagline: 'Their product-tile wall, with my work as the lineup.',
    appliedOn: '2026-07-05',
  },
  {
    id: 'nym',
    company: 'Nym',
    role: 'Software Engineer (Engine)',
    roleType: 'fullstack',
    url: 'https://bar-for-nym.vercel.app',
    domain: 'nym.health',
    accent: '#03B5E1',
    tagline: 'Their navy engine room, redrawn dash streams and all.',
    appliedOn: '2026-07-05',
  },
  {
    id: 'joomsy',
    company: 'Joomsy',
    role: 'Application site',
    roleType: 'other',
    url: 'https://bar-for-joomsy.vercel.app',
    domain: 'joomsy.com',
    accent: '#FFCC00',
    tagline: 'Their googly-eyed yellow world, every graphic hand-drawn.',
    appliedOn: '2026-07-05',
  },
  {
    id: 'guardio',
    company: 'Guardio',
    role: 'Fullstack Growth Engineer',
    roleType: 'fullstack',
    url: 'https://bar-for-guardio.vercel.app',
    domain: 'guard.io',
    accent: '#2E69FF',
    tagline: 'Floating proof cards in their pill-and-navy language.',
    appliedOn: '2026-07-05',
  },
  {
    id: 'alice',
    company: 'Alice',
    role: 'AI Software Engineer',
    roleType: 'ai',
    url: 'https://bar-for-alice.vercel.app',
    domain: 'alice.io',
    accent: '#108496',
    tagline: 'Wonderland brand with hand-coded SVG illustrations.',
    appliedOn: '2026-07-05',
  },
  {
    id: 'autofleet',
    company: 'Autofleet',
    role: 'Full Stack Developer',
    roleType: 'fullstack',
    url: 'https://bar-for-autofleet.vercel.app',
    domain: 'autofleet.io',
    accent: '#11A4FF',
    tagline: 'Their isometric city, redrawn as original SVG.',
    appliedOn: '2026-07-05',
  },
  {
    id: 'unframe',
    company: 'Unframe',
    role: 'Full Stack Software Engineer',
    roleType: 'fullstack',
    url: 'https://bar-for-unframe.vercel.app',
    domain: 'unframe.ai',
    accent: '#191919',
    tagline: 'Black and white bands with their signature gradient.',
    appliedOn: '2026-07-05',
  },
  {
    id: 'honeybook',
    company: 'HoneyBook',
    role: 'AI-native Builder',
    roleType: 'ai',
    url: 'https://bar-for-honeybook.vercel.app',
    domain: 'honeybook.com',
    accent: '#FFFA56',
    tagline: 'The pattern-setter: their clientflow look, my work grid.',
    appliedOn: '2026-07-04',
  },
  {
    id: 'aidome',
    company: 'Aidome',
    role: 'Full Stack Engineer, AI',
    roleType: 'fullstack',
    url: 'https://bar-for-aidome.vercel.app',
    domain: 'aidome.co',
    accent: '#ff003c',
    tagline: 'Their crimson control-plane language, my full stack proof.',
    appliedOn: '2026-07-03',
  },
  {
    id: 'classiq',
    company: 'Classiq',
    role: 'Software Engineer',
    roleType: 'other',
    url: 'https://bar-for-classiq.vercel.app',
    domain: 'classiq.io',
    accent: '#d7f75b',
    tagline: 'Quantum brand with their lime pills and circuit motif.',
    appliedOn: '2026-07-03',
  },
  {
    id: 'flare',
    company: 'Flare',
    role: 'AI Engineer',
    roleType: 'ai',
    url: 'https://bar-for-flare.vercel.app',
    domain: 'helloflare.com',
    accent: '#5b8a68',
    tagline: 'Their editorial serif calm with an agent-flow demo.',
    appliedOn: '2026-07-03',
  },
  {
    id: 'genielabs',
    company: 'GenieLabs',
    role: 'Full Stack Engineer',
    roleType: 'fullstack',
    url: 'https://bar-for-genielabs.vercel.app',
    domain: 'genielabs.tech',
    accent: '#FF1C74',
    tagline: 'Hot-pink LiveOps energy for game-studio content.',
    appliedOn: '2026-07-03',
  },
  {
    id: 'guidde',
    company: 'Guidde',
    role: 'Full Stack Engineer',
    roleType: 'fullstack',
    url: 'https://bar-for-guidde.vercel.app',
    domain: 'guidde.com',
    accent: '#0062FF',
    tagline: 'Their blue video-doc brand with a walkthrough player.',
    appliedOn: '2026-07-03',
  },
  {
    id: 'monday',
    company: 'monday.com',
    role: 'AI Software Engineer, RevAI',
    roleType: 'ai',
    url: 'https://bar-for-monday.vercel.app',
    domain: 'monday.com',
    accent: '#6161FF',
    tagline: 'Their live brand and a RevAI lead-qualification canvas.',
    appliedOn: '2026-07-03',
  },
  {
    id: 'qbiq',
    company: 'qbiq',
    role: 'Full Stack Developer',
    roleType: 'fullstack',
    url: 'https://bar-for-qbit.vercel.app',
    domain: 'qbiq.ai',
    accent: '#0040ff',
    tagline: 'Their perspective rays over a real-estate AI story.',
    appliedOn: '2026-07-03',
  },
  {
    id: 'descope',
    company: 'Descope',
    role: 'Full Stack Software Engineer',
    roleType: 'fullstack',
    url: 'https://bar-for-descope.vercel.app',
    domain: 'descope.com',
    accent: '#7DEDED',
    tagline: 'Their mint identity language, hexagon keys and all.',
    appliedOn: '2026-07-02',
  },
  {
    id: 'jeen-ai',
    company: 'Jeen.AI',
    role: 'Full Stack Engineer',
    roleType: 'fullstack',
    url: 'https://bar-for-jeen-ai.vercel.app',
    domain: 'jeen.ai',
    accent: '#dd9fe2',
    tagline: 'Cream and lilac enterprise AI with a governed-answer console.',
    appliedOn: '2026-07-02',
  },
  {
    id: 'esquare',
    company: 'e-square',
    role: 'Full Stack Developer',
    roleType: 'fullstack',
    url: 'https://bar-for-esquare.vercel.app',
    domain: 'e-square.io',
    accent: '#22d3ee',
    tagline: 'Glassmorphism and gradients in their Angular world.',
    appliedOn: '2026-07-01',
  },
  {
    id: 'jfrog',
    company: 'JFrog',
    role: 'GenAI and Competitive Intelligence Engineer',
    roleType: 'ai',
    url: 'https://bar-for-jfrog.vercel.app',
    domain: 'jfrog.com',
    accent: '#40BE46',
    tagline: 'Pipeline-flow graphics in JFrog green.',
    appliedOn: '2026-07-01',
  },
  {
    id: 'play48',
    company: 'Play48',
    role: 'Full Stack Game Engineer',
    roleType: 'fullstack',
    url: 'https://bar-for-play48.vercel.app',
    domain: 'play48.ai',
    accent: '#ee6a2c',
    tile: '#221610',
    tagline: 'Playable 2048 as the centerpiece.',
    appliedOn: '2026-06-30',
  },
  {
    id: 'prologic',
    company: 'Prologic',
    role: 'Full Stack Developer',
    roleType: 'fullstack',
    url: 'https://bar-for-prologic.vercel.app',
    domain: 'prologic.co.il',
    accent: '#f36f22',
    tagline: 'Their gear brand as a GenAI pipeline, right to left.',
    appliedOn: '2026-06-30',
  },
  {
    id: 'echo',
    company: 'Echo',
    role: 'Full Stack GenAI Engineer',
    roleType: 'ai',
    url: 'https://bar-for-echo.vercel.app',
    domain: 'echo.ai',
    accent: '#6aa7ff',
    tagline: 'Their iridescent palette over a full stack GenAI story.',
    appliedOn: '2026-06-30',
  },
  {
    id: 'orca',
    company: 'Orca AI',
    role: 'AI Systems Engineer',
    roleType: 'ai',
    url: 'https://bar-for-orca.vercel.app',
    domain: 'orca-ai.io',
    accent: '#5fe3d5',
    tagline: 'Navy ocean with a WebGL whale-tail shader.',
    appliedOn: '2026-06-30',
  },
  {
    id: 'ourritual',
    company: 'OurRitual',
    role: 'Generative AI Engineer',
    roleType: 'ai',
    url: 'https://bar-for-ourritual.vercel.app',
    domain: 'ourritual.com',
    accent: '#e5654b',
    tagline: 'Their warm palette around generative AI work.',
    appliedOn: '2026-06-30',
  },
  {
    id: 'psistar',
    company: 'Psistar',
    role: 'Software Engineer',
    roleType: 'other',
    url: 'https://bar-for-psistar.vercel.app',
    domain: 'psistar.ai',
    accent: '#7886e8',
    tagline: 'Psi-field motif in their periwinkle.',
    appliedOn: '2026-06-30',
  },
  {
    id: 'datadog',
    company: 'Datadog',
    role: 'Software Engineer, AI Developer Workflows',
    roleType: 'ai',
    url: 'https://bar-for-datadog.vercel.app',
    domain: 'datadoghq.com',
    accent: '#632ca6',
    tagline: 'Their purple observability style as a light dashboard.',
    appliedOn: '2026-06-29',
  },
  {
    id: 'tenable',
    company: 'Tenable',
    role: 'Full Stack Engineer, Integrations Frameworks',
    roleType: 'fullstack',
    url: 'https://bar-for-tenable.vercel.app',
    domain: 'tenable.com',
    accent: '#d6f84c',
    tagline: 'Lime on charcoal with a rotating heptagon mark.',
    appliedOn: '2026-06-29',
  },
  {
    id: 'aidoc',
    company: 'Aidoc',
    role: 'Generative AI Engineer',
    roleType: 'ai',
    url: 'https://bar-for-aidoc.vercel.app',
    domain: 'aidoc.com',
    accent: '#060C40',
    tagline: 'Clinical-AI brand with my AI pipeline work up front.',
    appliedOn: '2026-06-28',
  },
  {
    id: 'cheq',
    company: 'CHEQ',
    role: 'AI Engineer',
    roleType: 'ai',
    url: 'https://bar-for-cheq.vercel.app',
    domain: 'cheq.ai',
    accent: '#fd0173',
    tagline: 'Their dark intelligence brand, hot-pink gradients included.',
    appliedOn: '2026-06-28',
  },
  {
    id: 'cover',
    company: 'Cover',
    role: 'AI Full Stack Developer',
    roleType: 'ai',
    url: 'https://bar-for-cover.vercel.app',
    domain: 'cover.co.il',
    accent: '#0153f4',
    tagline: 'Their navy insurtech look with a periwinkle glow.',
    appliedOn: '2026-06-28',
  },
  {
    id: 'cytactic',
    company: 'Cytactic',
    role: 'AI Engineer',
    roleType: 'ai',
    url: 'https://bar-for-cytactic.vercel.app',
    domain: 'cytactic.com',
    accent: 'oklch(0.56 0.235 289)',
    tagline: 'Threat-response violet with a live incident feel.',
    appliedOn: '2026-06-28',
  },
  {
    id: 'deloitte',
    company: 'Deloitte',
    role: 'Full Stack Engineer, R&D and Innovation Center',
    roleType: 'fullstack',
    url: 'https://bar-for-deloitte.vercel.app',
    domain: 'deloitte.com',
    accent: '#86BC25',
    tagline: 'The green Big Four brand around GenAI and RAG work.',
    appliedOn: '2026-06-28',
  },
  {
    id: 'hio',
    company: 'HiO',
    role: 'Full Stack Engineer',
    roleType: 'fullstack',
    url: 'https://bar-for-hio.vercel.app',
    domain: 'hio.ai',
    accent: '#0040ff',
    tagline: 'A working mini HiO inbox in their own brand.',
    appliedOn: '2026-06-28',
  },
  {
    id: 'novella',
    company: 'Novella',
    role: 'AI Engineer',
    roleType: 'ai',
    url: 'https://bar-for-novella.vercel.app',
    domain: 'bynovella.com',
    accent: '#371D41',
    tagline: 'Plum and gold for an AI-native brokerage.',
    appliedOn: '2026-06-28',
  },
  {
    id: 'playojo',
    company: 'PlayOJO',
    role: 'Frontend / Game Developer',
    roleType: 'other',
    url: 'https://bar-for-playojo.vercel.app',
    domain: 'playojo.com',
    accent: '#4921c5',
    tagline: 'A fully playable Phaser slot game.',
    appliedOn: '2026-06-28',
  },
  {
    id: 'questar',
    company: 'Questar',
    role: 'Full Stack Developer',
    roleType: 'fullstack',
    url: 'https://bar-for-questar.vercel.app',
    domain: 'questarauto.com',
    accent: '#240046',
    tagline: 'Indigo fleet-health brand with gradient accents.',
    appliedOn: '2026-06-28',
  },
  {
    id: 'willow',
    company: 'Willow',
    role: 'Forward Deployed Engineer',
    roleType: 'other',
    url: 'https://bar-for-willow.vercel.app',
    domain: 'withwillow.ai',
    accent: 'oklch(0.68 0.15 145)',
    tagline: 'An animated isometric forest world.',
    appliedOn: '2026-06-28',
  },
  {
    id: 'openai',
    company: 'OpenAI',
    role: 'Generic application',
    roleType: 'ai',
    url: 'https://bar-for-openai.vercel.app',
    domain: 'openai.com',
    accent: '#000000',
    tile: '#ffffff',
    tagline: 'Their chat-input hero and story-card grid, reframed as my build pipeline.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'anthropic',
    company: 'Anthropic',
    role: 'Generic application',
    roleType: 'ai',
    url: 'https://bar-for-anthropic.vercel.app',
    domain: 'anthropic.com',
    accent: '#141413',
    tile: '#FAF9F5',
    tagline: 'Their warm editorial serif and a hand-drawn manuscript centerpiece.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'lovable',
    company: 'Lovable',
    role: 'Generic application',
    roleType: 'fullstack',
    url: 'https://bar-for-lovable.vercel.app',
    domain: 'lovable.dev',
    accent: '#FF6154',
    tagline: 'Their gradient blur and floating chat card, built as my brief-to-ship loop.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'intel',
    company: 'Intel',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-intel.vercel.app',
    domain: 'intel.com',
    accent: '#0046C8',
    tile: '#ffffff',
    tagline: 'A pinned chip-card carousel and a dot-matrix silicon motif.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'keshet',
    company: 'Keshet',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-keshet.vercel.app',
    domain: 'keshetinternational.com',
    accent: '#252b3d',
    tile: '#ffffff',
    tagline: 'Rebuilt as mako, Keshet’s Hebrew news portal, right to left.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'base44',
    company: 'Base44',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-base44.vercel.app',
    domain: 'base44.com',
    accent: '#FF6A00',
    tagline: 'A vibe-coding prompt box that builds the case for hiring me.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'wiz',
    company: 'Wiz',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-wiz.vercel.app',
    domain: 'wiz.io',
    accent: '#0254EC',
    tagline: 'Their blueprint line-art, redrawn as a live security graph.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'payoneer',
    company: 'Payoneer',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-payoneer.vercel.app',
    domain: 'payoneer.com',
    accent: '#7B3FE4',
    tagline: 'Their rainbow ring sweeping a clean white hero.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'figma',
    company: 'Figma',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-figma.vercel.app',
    domain: 'figma.com',
    accent: '#A259FF',
    tagline: 'A design canvas with my work already shipped on it.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'similarweb',
    company: 'Similarweb',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-similarweb.vercel.app',
    domain: 'similarweb.com',
    accent: '#195AFE',
    tile: '#071033',
    tagline: 'Their glowing data-search widget, my work as the insights.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'ai21',
    company: 'AI21 Labs',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-ai21.vercel.app',
    domain: 'ai21.com',
    accent: '#212121',
    tile: '#FBFBFB',
    tagline: 'Their scan-line editorial world, my shipped-systems stack.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'stripe',
    company: 'Stripe',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-stripe.vercel.app',
    domain: 'stripe.com',
    accent: '#635BFF',
    tagline: 'Their gradient ribbon and a builds.ts code panel of my work.',
    appliedOn: '2026-07-06',
  },
  {
    id: 'lemonade',
    company: 'Lemonade',
    role: 'Generic application',
    roleType: 'other',
    url: 'https://bar-for-lemonade.vercel.app',
    domain: 'lemonade.com',
    accent: '#FF0083',
    tile: '#4A4A4A',
    tagline: 'Their checkbox policy cards, my skills as the bundle.',
    appliedOn: '2026-07-11',
  },
];

export const logoOf = (s: Site) => `/logos/${s.id}.png`;
export const shotOf = (s: Site) => `/shots/${s.id}.webp`;
